### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by aazkan** [deprint/toggle-read-only#5]
Argument to `path.dirname` must be a string
```
Object.dirname (/usr/share/atom/resources/app.asar/src/electron-shims.js:9:10)
<unknown> (/usr/share/atom/resources/app.asar/src/project.js:559:41)
Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
TextBuffer.setReadOnly (/home/azu/.atom/packages/toggle-read-only/lib/toggle-read-only.coffee:80:27)
TextEditor.setReadOnly (/home/azu/.atom/packages/toggle-read-only/lib/toggle-read-only.coffee:103:31)
```

**Comment by fstiewitz** [comment]
I need a bit more information. When did that message appear? When starting Atom? When using the package?

**Comment by aazkan** [comment]
Hi,  Yes, that is correct. Start up Atom, a notice appears on at the bottom right of Atom has 1 depreciation.. Clicking update finds nothing new. 

Atom version is
rpm -qi atom
Name        : atom
Version     : 1.15.0
Release     : 0.1
Architecture: x86_64
Install Date: Fri 24 Mar 2017 07:39:32 PM +08
Group       : Unspecified
Size        : 261840806
License     : MIT
Signature   : (none)
Source RPM  : atom-1.15.0-0.1.src.rpm
Build Date  : Thu 09 Mar 2017 04:22:12 AM +08
Build Host  : testing-docker-1063f07a-1514-464b-8c70-28a8025a2adf
Relocations : /usr 
URL         : https://atom.io/
Summary     : A hackable text editor for the 21st Century.
Description :
A hackable text editor for the 21st Century.
