### ISSUE TITLE
Cursor do not move on a simple click

### ISSUE THREAD

**Issue by Kinxil** [deprint/toggle-read-only#6]
Atom version : 1.43.0
All community package disabled but toggle-read-only.
The file is in read only mode.

Action 1 : Click
Expected : Text cursor move to closest character where the click happened, like any text editor
Result : Text cursor does not move

Action 2 : Click-And-Hold, move mouse cursor, Release-Click
Expected : Selected a text zone from the initial mouse cursor position to the final one, like any editor
Result : Selected a text zone from the beginning of the **previous selection initial mouse cursor position** to the **current selection final mouse cursor position** (the click-release part seems to work but not the click-hold, very much like Action 1)

Action 3 : Double click
Expected : On text, select a text token between two spaces. Outside text, select the closest text token from the left of the mouse cursor (Atom default behaviour)
Result : Select the word with above expected behaviour BUT **from the previous text cursor position** (likely to be linked to Action 1 result)

This is not much of a critical issue but it make selecting a text particularly awkward, which make copy paste inefficient without going back to read-write mode.

**Comment by fstiewitz** [comment]
I don't think there is much I can do here (or at least the code required to fix this would be several times larger than the current implementation). There is no official API for making editors read-only and the current implementation relied on undocumented behaviour, which was changed at some point in the past (I don't use Atom anymore).

The package is broken beyond repair at this point and I'll probably remove it next week or so.
